import CurrencyConverter from "@/components/CurrencyConverter";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { Divider, Grid } from "@mui/material";
import WalletDetails from "@/components/WalletDetails";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Neptune Mutual Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grid container>
          <Grid item lg={4}>
            <CurrencyConverter />
          </Grid>

          {/* <Divider orientation="vertical" flexItem/> */}
          <Grid item lg={7}>
            <WalletDetails />
          </Grid>
        </Grid>
      </main>
    </>
  );
}
